### ISSUE TITLE
new line shouldn't be required before fenced codeblock

### ISSUE THREAD

**Issue by hayd** [uranusjr/macdown#322]
It seems that a new line is required before a fenced code block, it shouldn't be. 

    text
    ```
    fenced code block
    ```

http://johnmacfarlane.net/babelmark2/?text=no+need+for+new+line%0A%60%60%60%0Abefore+fenced+code+block%0A%60%60%60

Presumably this is an issue upstream?

**Comment by uranusjr** [comment]
It is. We’re already working on an updated parser that should resolve this.

**Comment by RandyMcMillan** [comment]
This is still an issue.
![Screen Shot 2019-10-21 at 1 51 41 PM](https://user-images.githubusercontent.com/152159/67230589-8bdf5e00-f40b-11e9-8da1-7179ab66098e.png)
![Screen Shot 2019-10-21 at 1 51 47 PM](https://user-images.githubusercontent.com/152159/67230590-8bdf5e00-f40b-11e9-86d4-21d1e7d79f1b.png)

**Comment by RandyMcMillan** [comment]
code block with info strings is a real issue. Please conform to gh flavored markdown. It will make this software more useful to me and probably others. 


need newline
```shell
before fenced code block with info string
```

need newline

```shell
before fenced code block with info string
```

[Babelmark 2 - Compare markdown implementations.pdf](https://github.com/MacDownApp/macdown/files/3752325/Babelmark.2.-.Compare.markdown.implementations.pdf)
