### ISSUE TITLE
$ sign in text causes issues

### ISSUE THREAD

**Issue by pageaffairs** [uranusjr/macdown#489]
Ran into an odd thing today where if you have two $ signs within your text, the text in between them greys out and MD syntax no longer works *visually* (it still previews OK). E.g.

---

Lorem ipsum dolor sit amet $20, consectetur adipisicing elit. Debitis cum blanditiis omnis eligendi repellat.

\## Heading

porro quisquam iste sapiente assumenda, dicta, odit libero nihil? Quasi, $50 harum molestias explicabo ullam praesentium soluta.

---

Produces this:

<img width="988" alt="test" src="https://cloud.githubusercontent.com/assets/1506144/10959908/7de4af24-83d2-11e5-9ba9-0538f76e794c.png">

**Comment by cyvoit** [comment]
Same here with macdown 0.5.2/0.5.3 & Mac OS X 10.11.1

**Comment by wenbert** [comment]
Using Version 0.5.3 (697) on El Capitan 10.11.1 (15B42).
Can confirm this problem.

**Comment by laughingrice** [comment]
It may be confusing it with inline math

See in the preferences -> rendering -> Tex-like math syntax if it's activated as well as the child use dollar sign

**Comment by pageaffairs** [comment]
@laughingrice Interesting—although those options aren't activated in my case.

**Comment by uranusjr** [comment]
Unfortunately this is currently not fixable because we are not able to tweak editor highlighting dynamically like the previewing pane. I have been looking for a better syntax highlighter without luck for a while now.

**Comment by uranusjr** [comment]
(I submitted the previous comment prematurely.)

A cruel workaround is to make dollar signs escapable, i.e. you can write `Apple is \$5. Orange \$4`. This is compatible with other Markdown renderers too.

**Comment by pageaffairs** [comment]
> A cruel workaround is to make dollar signs escapable
Heh, not a bad solution, and better than nothing. Thanks for following up. :-)

**Comment by nhoizey** [comment]
I have also this issue, but escaping the `$` doesn't change anything in the Markdown side:
![macdown-dollar](https://cloud.githubusercontent.com/assets/78213/12705561/27bfc4f8-c874-11e5-93a0-fc2fc8e83316.png)

**Comment by aeromusek** [comment]
:+1: on hoping for a fix here...it causes total havoc when trying to document anything in the PHP world :grimacing:

**Comment by uranusjr** [comment]
@aeromusek This should be fixed, yes, but I think you’re better of putting code in (inline) code blocks. This will display fine:

    Read the `$_POST` to `$me`.

**Comment by aeromusek** [comment]
@uranusjr thanks for the follow-up. You're right — it's only fixed when the `$` symbol is inside backticks.
![screen shot 2016-03-17 at 9 21 51 pm](https://cloud.githubusercontent.com/assets/7685059/13865862/63839a92-ec86-11e5-9ecd-774e5d0d14cc.png)

**Comment by kevinfilteau** [comment]
Within code is fine, but the problem is when marking price $ 99.99.

**Comment by rupe** [comment]
Like @nhoizey, escaping does not solve the problem for me. I've actually started using the word 'dollars' after the number, when inline, or putting '(in dollars)' after the header for tables.

**Comment by jesus-cortex** [comment]
This is very frustrating to me. I have a document created with Mou, which causes the issues described here:

![captura de pantalla 2016-08-30 a las 8 33 02](https://cloud.githubusercontent.com/assets/19991157/18078544/694c9158-6e8c-11e6-9381-b077cb196d0e.jpg)

The thing is that if I copy that text into a new file, everything looks good:

![captura de pantalla 2016-08-30 a las 8 33 36](https://cloud.githubusercontent.com/assets/19991157/18078580/8ebdcfb0-6e8c-11e6-9631-a333cc941e85.jpg)

**Comment by yepes** [comment]
This is very frustrating to me. I have a document created with Mou, which causes the issues described here:

![captura de pantalla 2016-08-30 a las 8 33 02](https://cloud.githubusercontent.com/assets/1114453/18078680/271a47f2-6e8d-11e6-9c4c-543af2bed13c.jpg)


The thing is that if I copy that text into a new file, everything looks good:

![captura de pantalla 2016-08-30 a las 8 33 36](https://cloud.githubusercontent.com/assets/1114453/18078685/2bc76a46-6e8d-11e6-8bf4-ce64b3f8dd3b.jpg)

**Comment by pierow2k** [comment]
I am also experiencing this issue.  A lot of the Markdown that I write includes pricing information which makes the documents toggle between colors - somewhat negating the syntax highlighting feature.  

Like @nhoizey and @rupe, escaping does not solve the problem for me.  Similar to the workaround that @rupe proposed,I have started using **USD** instead of $ or \$ _but that is less than ideal_.

![2016-09-29-macdown](https://cloud.githubusercontent.com/assets/9472998/18961621/35894bfe-8633-11e6-9e62-e7876c6e9efd.jpg)

**Comment by CNG** [comment]
Also experiencing the issue with price information in blog posts I attempt to write with MacDown.

**Comment by alienresident** [comment]
I'm experiencing the same issue but I found a workaround. 

I'm using the HTML number code &#36; for $.

**Comment by pageaffairs** [comment]
@alienresident — Heh, good solution. :-)

**Comment by Jmuccigr** [comment]
So where are we on this? (And by "we", I of course mean "you". ;-) )

**Comment by franklinyu** [comment]
@Jmuccigr I just read through this thread. Among the three approaches:

### bare dollar sign

MacDown doesn't work with this, but I don't think it' a good way to write bare dollar sign, because on many Markdown system that supports math with `$`, this will mess things up. It's difficult to decide whether a dollar sign means "the beginning of math" or "a plain dollar sign", for example in

```markdown
Do you mean $14 or $40?
```

and in

```markdown
Clearly $110_2 = 6_{10}$ (subscript for base in numeral system).
```

### HTML entities

Works perfectly in MacDown, and will surely work in any editor/renderer. The code is not readable though.

### escape by backslash

I like this approach and believe MacDown should support this. I didn't research much, but I believe most editors and renderers should work with it. Currently preview pane in MacDown works great, but syntax highlight fails (as noted by @nhoizey). I'm not familiar enough to code to decide whether it belongs to upstream (PEG in this case); I tried their sample Cocoa app, which doesn't seem to highlight math at all.

**Comment by Jmuccigr** [comment]
It's interesting to me that the renderer handles it fine (as does pandoc), while the editor doesn't. Clearly there's a fairly good algorithm for determining the difference between currency and math.

That said, surely MacDown should support \ escaping (everywhere?).

**Comment by franklinyu** [comment]
> Clearly there's a fairly good algorithm for determining the difference between currency and math.

@Jmuccigr Did you mean the bare dollar sign or the escaped dollar sign?

**Comment by Jmuccigr** [comment]
Bare.

**Comment by franklinyu** [comment]
Then the renderer *didn't* handles it fine. I'll try Pandoc to see its behavior.

**Comment by franklinyu** [comment]
Pandoc [restrict the conversion to math](http://pandoc.org/MANUAL.html#math) into

> The opening `$` must have a non-space character immediately to its right, while the closing `$` must have a non-space character immediately to its left, and must not be followed immediately by a digit. Thus, `$20,000 and $30,000` won’t parse as math.

Therefore

```markdown
We know what $ E = m c^2 $ means.
```

won't work. By Pandoc's choice I guess very few users do this.

**Comment by Jmuccigr** [comment]
I may be confused here. :-) For me, the left side of a MacDown window (the editor, right?) doesn't handle the $ right, but the right side (the renderer, right?) does. This is with the tex-math option checked and $ as inline delimiter checked as well.

The pandoc rule seems pretty good to me. There are some edge cases, but supporting \-escaping should handle those.

**Comment by franklinyu** [comment]
That's different from what I saw. My MacDown converts this

```markdown
Do you mean $14 or $40?
```

into HTML

```html
<p>Do you mean \(14 or \)40?</p>
```

which is rendered by MathJax as

![dollar-sign](https://cloud.githubusercontent.com/assets/3153452/23051080/5549e9f6-f494-11e6-86fe-0a905d32a89b.png)

**Comment by Jmuccigr** [comment]
Sorry, you're right.

I think I was observing the treatment of multiple $ in the text with tex-math off, not on. There the editor highlights the text, but the renderer leaves it alone.

**Comment by Jmuccigr** [comment]
BTW, it would be nice if the editor would not do any syntax highlighting when the tex-math option in the prefs is unchecked.

**Comment by manngo** [comment]
For what it’s worth, I think the need for a simple `$` sign is probably greater than the need for Maths processing.

If I use `$` for coding samples (such as for PHP or jQuery), I can wrap the expression in ticks or put it all in a code fence. If not, it shouldn’t be so complicated.

**Comment by TruePath** [comment]
I just added a pull request that should allow one to use \$ in text to avoid having text delimited by $ interpreted as math.  Basically $ wasn't included as an escapable charachter way down deep in the markdown parser being used to do the styling but once included it seems to work fine for me.

If you really desperate you can go look at the pull request I created and make the change yourself and recompile.  It is literally a change of adding one character.

**Comment by pierow2k** [comment]
Thank you @TruePath !  This issue has caused so many problems in my project workflow - happy to see that it is finally being addressed.

**Comment by TruePath** [comment]
Ironic.  Spending time fucking around trying to fix this caused me lots of problems with my workflow today :-).

Anyway glad I could help..though reluctant to assume I have until the patch is accepted.  I’m pretty sure this fix won’t break anything (I’m using it without problems) but waiting for the maintainer to check it out and review it.

**Comment by CNG** [comment]
Thanks @TruePath – nice name, btw… I inadvertently typed “TruePatch”!

In reading "to use $ in text" in your first line, I got overly excited and didn’t realize you meant "to use `\$` in text. Once I figured that out a minute later, I can at least report MacDown is working fine for me as well so far.

Of course it still would be much better for the syntax highlighter to work as well as the preview renderer. I use Markdown for simply formatted and readable plain text files. Extra syntax means less readability. Then it looks like slash escaping is not universal in Markdown renderers. The GitHub parser does convert `\$1.23` to `$1.23`. The Markdown.pl (v1.03) included with the latest version of Movable Type keeps `\$` as is, so unfortunately I still must use alternate workarounds.

This is not to take away from the utility of allowing the escape for people whose workflows are compatible. Just be sure to check how it is handled wherever your Markdown documents are being used!

---

Note for anyone who does not use Ruby or Xcode much (like me), this is how I compiled...

```sh
git clone git@github.com:MacDownApp/macdown.git && cd macdown
git fetch origin pull/831/head:patch-831
git checkout patch-831
git submodule init
git submodule update
sudo gem install bundler
bundle install
bundle exec pod install
open MacDown.xcworkspace
```

Then in Xcode, I went to the menu _Product_ > _Archive_, then _Export..._ on the right, then _Export as a macOS App_.

**Comment by head1328** [comment]
with 0.7.1 on macOS 10.12.6

    ```
    ~ $ any command...
    ```

![macdown](https://user-images.githubusercontent.com/2060042/29354852-0ac76f0c-826f-11e7-89a7-22811f5b65dc.png)

**Comment by boompig** [comment]
Hi all, is there any fix or workaround? 

Both (1) backslash escaping, and (2) disabling MathTex entirely, do not work as workarounds.

My 2c: As others have said, the use case for prices is much more common than MathTex or similar. I don't believe the Markdown official spec (CommonMark) does not say anything about dollar signs. It seems to me that folks who are interested in special features for dollar signs should have to opt-in, and the default behaviour should be closer to CommonMark and just treat it as a regular character.

Love this editor, this is probably my biggest nit 😄

**Comment by SimplGy** [comment]
Sounds like the correct fix is to only syntax highlight if there's a space to the right of the `$`. (https://github.com/MacDownApp/macdown/issues/489#issuecomment-280515599)

Any concerns with this approach, or is this ready for a PR?

**Comment by FranklinYu** [comment]
@SimplGy I kind of forget the context but IIUC this should be fixed [upstream](https://github.com/ali-rantakari/peg-markdown-highlight). You can submit PR there.

**Comment by SimplGy** [comment]
Is the upstream project still maintained?

I see valid and tiny PRs that are years old. Eg:
https://github.com/ali-rantakari/peg-markdown-highlight/pull/20

**Comment by lukaslabryszewski** [comment]
Great App, but this $ sign issue is my biggest gripe with it. Unfortunately still not addressed or maintained.

**Comment by yourcontact** [comment]
HTML number code `&#36;` (as a substitute for `$`) prevents the text to grey out - in my MD editor; see  https://github.com/MacDownApp/macdown/issues/489#issuecomment-270757201.

Still in my MD editor, the `\$` workaround does not prevent the text to grey out.

FYI I have _Tex-like math Syntax_ unchecked.

**Comment by jeffsf** [comment]
Still a problem, and a very annoying one. Version 0.7.1 (870)

**Comment by ecmonsen** [comment]
Also still a problem in 0.7.3. Backslash escape doesn't prevent text becoming grayed out. Using `&#36;` works as expected in the preview pane but I would also like my document to be readable as raw text.

**Comment by WhiteboxSoftwareLtd** [comment]
My workaround is to use a `<!-- $ -->` tag following each use of the `$` sign.

Markdown:

```
## About Nicolas Darvas

Nicolas Darvas (1920–1977) was a dancer, self-taught investor, and author. He is best known for his book, "How I Made $2,000,000<!-- $ --> in the Stock Market."
```

Renders as:

## About Nicolas Darvas

Nicolas Darvas (1920–1977) was a dancer, self-taught investor, and author. He is best known for his book, "How I Made $2,000,000 in the Stock Market."

---

While slightly annoying one has to do this, to me, it is still the best workaround.

**Comment by pageaffairs** [comment]
@WhiteboxSoftwareLtd — Hah, nice solution. :-)
